'use client';
import {useState,useEffect} from 'react';
import {Landmark,ExternalLink,Check,RefreshCw,Plus,Trash2,ShieldCheck,KeyRound} from 'lucide-react';
type Connection={id:string;name:string;syncedAt:string|null;status:string};
export default function Banks({onChange}:{onChange:()=>Promise<void>}){
 const [connections,setConnections]=useState<Connection[]>([]),[configured,setConfigured]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(''),[clientId,setClientId]=useState(''),[clientSecret,setClientSecret]=useState(''),[name,setName]=useState(''),[itemId,setItemId]=useState(''),[showConfig,setShowConfig]=useState(false);
 async function refresh(){try{const r=await fetch('/api/banks');const d:any=await r.json();if(!r.ok)throw Error(d.error);setConnections(d.connections);setConfigured(d.configured);setError('')}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{refresh()},[]);
 async function post(action:string,data:any={}){const r=await fetch('/api/banks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...data})});const d:any=await r.json();if(!r.ok)throw Error(d.error);return d}
 async function configure(e:any){e.preventDefault();setBusy('configure');setError('');setMessage('');try{await post('configure',{clientId,clientSecret});setClientId('');setClientSecret('');setShowConfig(false);await refresh();setMessage('Acesso validado e salvo. Agora adicione as conexões do Meu Pluggy.')}catch(e:any){setError(e.message)}finally{setBusy('')}}
 async function add(e:any){e.preventDefault();setBusy('add');setError('');setMessage('');try{await post('add',{name,itemId:itemId.trim()});setName('');setItemId('');await refresh();setMessage('Conexão adicionada. Clique em Importar para trazer os dados disponíveis.')}catch(e:any){setError(e.message)}finally{setBusy('')}}
 async function sync(c:Connection){setBusy(c.id);setError('');setMessage('');try{const d=await post('sync',{itemId:c.id});await refresh();await onChange();setMessage(`${c.name}: ${d.accounts} contas/cartões e ${d.transactions} lançamentos importados.${d.skipped?' Contas em outras moedas ou sem suporte ficaram de fora.':''}${d.partial?' O provedor informou uma coleta parcial. Confira o Meu Pluggy.':''}`)}catch(e:any){setError(e.message)}finally{setBusy('')}}
 async function remove(c:Connection){if(!confirm(`Remover ${c.name} e os registros importados desta conexão? Os lançamentos manuais serão mantidos. Para revogar o consentimento no banco, use o Meu Pluggy.`))return;setBusy(c.id);setError('');try{const r=await fetch('/api/banks?id='+encodeURIComponent(c.id),{method:'DELETE'});const d:any=await r.json();if(!r.ok)throw Error(d.error);await refresh();await onChange();setMessage('Conexão e registros importados removidos do Livre.')}catch(e:any){setError(e.message)}finally{setBusy('')}}
 return <div className="banks"><div className="bank-intro"><span className="bank-symbol"><Landmark size={28}/></span><div><h2>Seus bancos no Livre</h2><p>Meu Pluggy · uso pessoal · até 5 conexões</p></div><span className="bank-count">{connections.length}/3 para seu teste</span></div>{loading&&<p className="mini-empty">Carregando conexões…</p>}{error&&<div className="error" role="alert">{error}<button onClick={refresh} disabled={!!busy}>Tentar novamente</button></div>}{message&&<div className="success" role="status"><Check size={18}/>{message}</div>}
 <section className="panel bank-guide"><div className="panel-title"><h3>Prepare suas três conexões</h3><a href="https://meu.pluggy.ai/api-guide" target="_blank" rel="noopener noreferrer" className="text-button">Guia oficial <ExternalLink size={14}/></a></div><ol><li><span>1</span><div><strong>Conecte seus bancos</strong><p>Crie sua conta gratuita e autorize três bancos no Meu Pluggy.</p><a className="secondary" href="https://meu.pluggy.ai/" target="_blank" rel="noopener noreferrer">Abrir Meu Pluggy <ExternalLink size={14}/></a></div></li><li><span>2</span><div><strong>Autorize o acesso pessoal</strong><p>No Dashboard, abra a aplicação demo e use o conector MeuPluggy (200) para acessar as conexões. Copie as credenciais da aplicação e o Item ID de cada conexão proxy.</p><a className="secondary" href="https://dashboard.pluggy.ai/" target="_blank" rel="noopener noreferrer">Abrir Dashboard <ExternalLink size={14}/></a></div></li><li><span>3</span><div><strong>Importe para o Livre</strong><p>Configure o acesso abaixo, adicione os três Item IDs e importe os dados de cada conexão.</p></div></li></ol></section>
 <div className="bank-setup-grid"><section className="panel bank-form"><div className="panel-title"><h3><KeyRound size={18}/> Acesso à aplicação demo</h3>{configured&&<span className="status done">Configurado</span>}</div>{!configured||showConfig?<form onSubmit={configure}><label>Client ID<input autoComplete="off" required value={clientId} onChange={e=>setClientId(e.target.value)} placeholder="Client ID da aplicação demo" maxLength={200}/></label><label>Client Secret<input type="password" autoComplete="new-password" required value={clientSecret} onChange={e=>setClientSecret(e.target.value)} placeholder="Client Secret da aplicação demo" maxLength={500}/></label><p className="bank-hint"><ShieldCheck size={17}/> Credenciais criptografadas no servidor. Não informe senha ou código do seu banco aqui.</p><button className="primary" disabled={!!busy||loading}>{busy==='configure'?'Validando…':'Validar e salvar acesso'}</button></form>:<><div className="bank-ready"><ShieldCheck size={28}/><strong>Acesso pessoal configurado</strong><p>Suas credenciais não são exibidas no navegador.</p></div><button className="secondary" disabled={!!busy} onClick={()=>setShowConfig(true)}>Trocar credenciais</button></>}</section><section className="panel bank-form"><div className="panel-title"><h3><Plus size={18}/> Adicionar conexão</h3><span className="tag">{connections.length} de 5</span></div><form onSubmit={add}><label>Nome do banco<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: Meu banco principal" maxLength={80}/></label><label>Item ID do conector MeuPluggy<input required autoComplete="off" value={itemId} onChange={e=>setItemId(e.target.value)} placeholder="ID da conexão proxy no Dashboard" maxLength={36}/></label><p className="bank-hint">Use o Item ID da aplicação demo. O ID original de dentro do Meu Pluggy pode não ser acessível por essa aplicação.</p><button className="primary" disabled={!configured||!!busy||loading||connections.length>=5}>{busy==='add'?'Verificando…':'Adicionar conexão'}</button>{!configured&&<small className="bank-hint">Configure o acesso primeiro.</small>}</form></section></div>
 <section className="panel bank-connections"><div className="panel-title"><h3>Suas conexões</h3><span className="tag">Somente leitura</span></div>{connections.map(c=><div className="bank-connection" key={c.id}><span className="account-icon"><Landmark size={21}/></span><div><strong>{c.name}</strong><small>{c.syncedAt?'Importado em '+new Date(c.syncedAt).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}):'Dados ainda não importados'}</small></div><button className="secondary" disabled={!!busy} onClick={()=>sync(c)}><RefreshCw size={16} className={busy===c.id?'spin':''}/>{busy===c.id?'Importando…':'Importar'}</button><button disabled={!!busy} className="remove-bank" aria-label={'Remover '+c.name} onClick={()=>remove(c)}><Trash2 size={17}/></button></div>)}{!connections.length&&<div className="bank-slots">{[1,2,3].map(i=><div key={i}><Landmark size={24}/><strong>Conexão {i}</strong><small>Aguardando seu banco</small></div>)}</div>}<p className="bank-hint">Importamos saldos e lançamentos disponíveis dos últimos 90 dias em reais. O Meu Pluggy atualiza a origem diariamente; o botão Importar traz o que já estiver disponível, sem forçar uma atualização no banco. Novas importações substituem o histórico importado desta conexão e mantêm as categorias que você ajustou. Transferências entre suas contas podem aparecer como receita e despesa.</p><p className="bank-hint">Para cancelar o compartilhamento, gerencie o consentimento no Meu Pluggy ou no seu banco. Remover do Livre apaga apenas a conexão e seus registros locais.</p></section></div>
}
