import type {FinanceRecord,CardBill} from '../lib/finance-summary';
const date=(value:string)=>value.split('-').reverse().join('/');
export default function CardBills({cards,transactions,month,shown}:{cards:FinanceRecord[];transactions:FinanceRecord[];month:string;shown:(n:number)=>string}){
 return <section className="panel bill-panel"><div className="panel-title"><h3>Faturas e parcelas</h3><span className="tag">{month.split('-').reverse().join('/')}</span></div><p className="bill-note">Valores e vencimentos informados pelo banco. O estado do pagamento deve ser confirmado no aplicativo do cartão.</p>{cards.map(card=>{
 const bills:CardBill[]=(card.data.bills||[]).filter((bill:CardBill)=>bill.dueDate.startsWith(month));
 const purchases=transactions.filter(t=>t.data.card===card.id&&t.data.date?.startsWith(month)&&!t.data.cardSettlement);
 const installments=purchases.filter(t=>t.data.installment);
 const spending=purchases.reduce((s,t)=>s+(t.data.type==='expense'?1:-1)*t.data.amount,0);
 return <div className="bill-card" key={card.id}><div className="bill-card-heading"><strong>{card.data.name}</strong><span className="tag">{card.data.source==='pluggy'?'Banco conectado':'Cartão manual'}</span></div><div className="bill-spending"><span>Compras menos estornos no mês</span><strong>{shown(spending)}</strong></div>{bills.map(bill=><div className="bill-entry" key={bill.id}><div><strong>Vencimento {date(bill.dueDate)}</strong><small>{bill.closingDate?'Fechamento '+date(bill.closingDate):'Fechamento não informado'}</small></div><strong>{shown(bill.total)}</strong><p>Pagamento mínimo: {bill.minimum===null?'Não informado':shown(bill.minimum)}</p></div>)}{!bills.length&&<p className="bill-note">{card.data.source!=='pluggy'?'Faturas oficiais disponíveis nos cartões conectados.':!card.data.billsStatus?'Importe novamente em Open Finance para buscar as faturas.':card.data.billsStatus==='unavailable'?'Faturas indisponíveis nesta importação. Confira no banco.':'Nenhuma fatura informada para este mês.'}</p>}{card.data.billsStatus==='unavailable'&&bills.length>0&&<p className="bill-warning">A consulta de faturas falhou. Os valores exibidos são da importação anterior.</p>}{card.data.billsUpdatedAt&&<p className="bill-note">Faturas consultadas em {new Date(card.data.billsUpdatedAt).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}</p>}{installments.length>0&&<details className="installment-list"><summary>Parcelas informadas neste mês ({installments.length})</summary>{installments.map(t=><div key={t.id}><span>{t.data.name}<small>Parcela {t.data.installment.number} de {t.data.installment.total}</small></span><strong>{shown(t.data.amount)}</strong></div>)}<p className="bill-note">Exibimos apenas parcelas recebidas do banco, sem criar cobranças futuras estimadas.</p></details>}</div>
 })}{!cards.length&&<p className="mini-empty">Conecte ou cadastre um cartão para acompanhar suas faturas.</p>}</section>
}
