import {financialInsights} from '../lib/finance-insights';
import {type FinanceRecord} from '../lib/finance-summary';
import {ArrowRight,CalendarDays,Check,Target,TriangleAlert} from 'lucide-react';

type Props={records:FinanceRecord[];month:string;today:string;view:string;shown:(value:number)=>string;navigate:(view:string)=>void;toggle:(record:FinanceRecord)=>Promise<void>};
const dateLabel=(date:string)=>date.split('-').reverse().join('/');
export default function FinanceInsights({records,month,today,view,shown,navigate,toggle}:Props) {
  const info=financialInsights(records,month,today);
  const goals=records.filter(r=>r.kind==='goal');
  const accounts=records.filter(r=>r.kind==='account');
  const transactions=records.filter(r=>r.kind==='transaction');
  const metrics=(items:{label:string;value:number|null;note:string;tone?:string}[])=><div className="insight-metrics">{items.map(item=><div className="insight-stat" key={item.label}><span>{item.label}</span><strong className={item.tone}>{item.value===null?'—':shown(item.value)}</strong><small>{item.note}</small></div>)}</div>;
  const agenda=<section className="panel agenda-panel"><div className="panel-title"><h3><CalendarDays size={18}/> Contas a pagar e receber</h3><span className="tag">{info.pending.length} pendências no mês</span></div>{info.pending.length?<div className="agenda-list">{info.pending.map(row=>{
    const overdue=row.data.date<today;
    return <div className="agenda-entry" key={row.id}><div className={'agenda-date '+(overdue?'red':'')}><strong>{row.data.date.slice(8)}</strong><small>{row.data.date.slice(5,7)}</small></div><div className="agenda-description"><strong>{row.data.name}</strong><small>{row.data.category} · {dateLabel(row.data.date)}</small><span className={'status '+(overdue?'expense':'pending')}>{overdue?'Vencido':row.data.date===today?'Vence hoje':'A vencer'} · {row.data.type==='income'?'A receber':'A pagar'}</span></div><strong className={row.data.type==='income'?'green':''}>{shown(row.data.amount)}</strong>{row.data.source!=='pluggy'&&<button className="secondary" onClick={()=>toggle(row)} aria-label={'Confirmar '+row.data.name}><Check size={16}/><span>{row.data.type==='income'?'Recebido':'Pago'}</span></button>}</div>;
  })}</div>:<div className="mini-empty">Nenhuma pendência neste mês. Cadastre um lançamento com a opção de pagamento desmarcada para acompanhar o vencimento.</div>}</section>;
  if(view==='Agenda')return <>{metrics([{label:'A pagar',value:info.payable,note:'Despesas pendentes',tone:'red'},{label:'A receber',value:info.receivable,note:'Receitas pendentes',tone:'green'},{label:'Vencidos',value:info.overdue.reduce((s,r)=>s+r.data.amount,0),note:`${info.overdue.length} pagamentos e recebimentos em atraso`}])}{agenda}</>;
  if(view==='Contas')return <>{metrics([{label:'Saldo consolidado',value:info.balance,note:`${accounts.length} contas cadastradas e valores sem conta`},{label:'A pagar no mês',value:info.payable,note:'Pendências fora dos cartões',tone:'red'},{label:'A receber no mês',value:info.receivable,note:'Receitas a confirmar',tone:'green'}])}<p className="section-note">O saldo atual usa o último valor importado dos bancos e os movimentos realizados nas contas manuais. O mês selecionado define os indicadores de entradas e saídas.</p></>;
  if(view==='Cartões')return metrics([{label:'Compras líquidas no mês',value:info.cardSpending,note:'Compras menos estornos; não inclui pagamento da fatura'},{label:'Limite total cadastrado',value:records.filter(r=>r.kind==='card').reduce((s,r)=>s+r.data.amount,0),note:'Soma dos limites dos cartões'},{label:'Faturas informadas',value:records.filter(r=>r.kind==='card').flatMap(r=>r.data.bills||[]).filter(b=>b.dueDate.startsWith(month)).reduce((s,b)=>s+b.total,0),note:'Total recebido dos bancos; confira a situação do pagamento'}]);
  if(view==='Orçamentos')return <>{metrics([{label:'Limites mensais',value:info.budgets.reduce((s,b)=>s+b.data.amount,0),note:`${info.budgets.length} orçamentos cadastrados`},{label:'Consumo nas categorias',value:info.budgets.reduce((s,b)=>s+b.used,0),note:'Inclui compras no cartão e desconta estornos'},{label:'Limites ultrapassados',value:info.budgets.reduce((s,b)=>s+Math.max(0,-b.remaining),0),note:`${info.budgets.filter(b=>b.percent>100).length} orçamentos acima do limite`,tone:'red'}])}<p className="section-note">Os limites se repetem a cada mês. Compras no cartão entram no consumo da categoria; o pagamento da fatura fica no fluxo das contas. Orçamentos da mesma categoria se sobrepõem.</p></>;
  if(view==='Metas')return <>{metrics([{label:'Total dos objetivos',value:goals.reduce((s,g)=>s+g.data.amount,0),note:`${goals.length} metas cadastradas`},{label:'Valor guardado',value:goals.reduce((s,g)=>s+(g.data.saved||0),0),note:'Valores informados por você',tone:'green'},{label:'Falta alcançar',value:goals.reduce((s,g)=>s+Math.max(0,g.data.amount-(g.data.saved||0)),0),note:`${goals.filter(g=>(g.data.saved||0)>=g.data.amount).length} metas concluídas`}])}<p className="section-note">O valor guardado acompanha seu progresso e não altera o saldo das contas.</p></>;
  if(!['Visão geral','Relatórios'].includes(view))return null;
  const previous=info.history[4];
  const ceiling=Math.max(1,...info.history.flatMap(item=>[item.income,item.expense]));
  return <>
    {metrics([{label:'Recebido até hoje',value:info.realizedIncome,note:'Entradas confirmadas no mês',tone:'green'},{label:'Pago até hoje',value:info.realizedExpense,note:'Saídas confirmadas no mês',tone:'red'},{label:'A pagar / a receber',value:info.payable,note:`A receber: ${shown(info.receivable)}`},{label:'Saldo após pendências',value:info.projected,note:info.projected===null?'Projeção indisponível para mês passado':'Saldo atual + pendências de hoje até o fim do mês'}])}
    {view==='Visão geral'&&<div className="dashboard-grid insight-grid"><section className="panel"><div className="panel-title"><h3>Seu mês em foco</h3><button className="text-button" onClick={()=>navigate('Relatórios')}>Relatórios <ArrowRight size={14}/></button></div><div className="focus-row"><TriangleAlert size={18} className={info.overdue.length?'red':''}/><div><strong>{info.overdue.length?`${info.overdue.length} pendências vencidas`:'Nenhuma pendência vencida no mês'}</strong><small>{info.overdue.length?'Confira os pagamentos e recebimentos em atraso.':'Acompanhe as próximas datas na agenda.'}</small></div><button className="secondary" onClick={()=>navigate('Agenda')}>Agenda</button></div><div className="focus-row"><Target size={18}/><div><strong>{info.budgets.filter(b=>b.percent>=80).length} orçamentos em atenção</strong><small>Consumo a partir de 80% do limite mensal.</small></div><button className="secondary" onClick={()=>navigate('Orçamentos')}>Ver limites</button></div><div className="focus-row"><Check size={18}/><div><strong>{goals.filter(g=>(g.data.saved||0)>=g.data.amount).length} metas concluídas</strong><small>{goals.length} objetivos acompanhados.</small></div><button className="secondary" onClick={()=>navigate('Metas')}>Ver metas</button></div></section><section className="panel"><div className="panel-title"><h3>Comparação com o mês anterior</h3><span className="tag">{previous.month.split('-').reverse().join('/')}</span></div>{previous.count||info.cash.length?<><div className="comparison-row"><span>Entradas</span><strong>{shown(info.income-previous.income)}</strong></div><div className="comparison-row"><span>Saídas</span><strong>{shown(info.expense-previous.expense)}</strong></div><div className="comparison-row"><span>Resultado do mês anterior</span><strong>{shown(previous.net)}</strong></div><p className="section-note">Diferença em reais: mês selecionado menos mês anterior. Inclui pendências cadastradas; meses sem lançamentos têm total zero.</p></>:<div className="mini-empty">Cadastre ou importe lançamentos para comparar os meses.</div>}</section></div>}
    {view==='Relatórios'&&<section className="panel history-panel"><div className="panel-title"><h3>Evolução em seis meses</h3><span className="tag">Entradas e saídas das contas</span></div><div className="history-chart">{info.history.map(item=><div className="history-month" key={item.month}><div className="history-bars"><div className="income-bar" style={{height:Math.max(2,item.income/ceiling*120)}} title={'Entradas: '+shown(item.income)}/><div className="expense-bar" style={{height:Math.max(2,item.expense/ceiling*120)}} title={'Saídas: '+shown(item.expense)}/></div><span>{item.month.slice(5)}/{item.month.slice(2,4)}</span><strong className={item.net<0?'red':'green'}>{shown(item.net)}</strong></div>)}</div><div className="history-legend"><span className="green">● Entradas</span><span className="red">● Saídas</span><span>Valores abaixo das barras: resultado do mês</span></div><div className="table-wrap"><table><caption className="section-note">Totais por mês, incluindo pendências cadastradas</caption><thead><tr><th>Mês</th><th>Entradas</th><th>Saídas</th><th>Resultado</th></tr></thead><tbody>{info.history.map(item=><tr key={item.month}><td>{item.month.split('-').reverse().join('/')}</td><td>{shown(item.income)}</td><td>{shown(item.expense)}</td><td className={item.net<0?'red':'green'}>{shown(item.net)}</td></tr>)}</tbody></table></div></section>}
    {view==='Visão geral'&&<div className="panel forecast-note"><strong>Sobre a projeção</strong><p>Considera apenas os lançamentos pendentes nas contas. Faturas, parcelas futuras, juros e receitas ainda não cadastradas não são estimados. Pendências vencidas precisam ser revisadas na agenda.</p></div>}
  </>;
}
