import {isSupabase,sbStore} from '../../../lib/storage';

const categories=['Moradia','Alimentação','Transporte','Saúde','Lazer','Educação','Compras','Salário','Outros'];
function sameOrigin(req:Request){return req.headers.get('origin')===new URL(req.url).origin}
function valid(x:any){return x && ['transaction','account','card','budget','goal'].includes(x.kind)&&x.data&&typeof x.data.name==='string'&&x.data.name.trim().length>0&&x.data.name.length<=120&&Number.isFinite(x.data.amount)&&x.data.amount>=(['transaction','budget','goal'].includes(x.kind)?0.01:0)&&x.data.amount<=1e12&&!x.data.source;}
export async function GET(){try{if(isSupabase())return Response.json({records:(await sbStore('read')).records},{headers:{'Cache-Control':'no-store'}});throw Error('Storage unavailable');}catch(e){console.error(e);return Response.json({error:'Não foi possível carregar seus dados. Tente novamente.'},{status:503});}}
export async function POST(req:Request){try{if(!sameOrigin(req))return Response.json({error:'Reabra o Livre para continuar.'},{status:403});const x:any=await req.json();if(!valid(x))return Response.json({error:'Confira o nome e o valor.'},{status:400});const id=crypto.randomUUID();if(isSupabase()){const record={id,kind:x.kind,data:x.data};await sbStore('save',record);return Response.json(record,{status:201})}throw Error('Storage unavailable');}catch(e){console.error(e);return Response.json({error:'Não foi possível salvar. Seus campos foram preservados.'},{status:503});}}
export async function PUT(req:Request){try{if(!sameOrigin(req))return Response.json({error:'Reabra o Livre para continuar.'},{status:403});const x:any=await req.json();if(typeof x.id!=='string')return Response.json({error:'Dados inválidos.'},{status:400});const row:any=isSupabase()?(await sbStore('read')).records.find((r:any)=>r.id===x.id):null;if(!row)return Response.json({error:'Registro não encontrado.'},{status:404});const old=isSupabase()?row.data:JSON.parse(row.data);if(old.source==='pluggy'){if(row.kind!=='transaction'||!categories.includes(x.data?.category))return Response.json({error:'Este registro é atualizado pelo banco.'},{status:400});x.kind=row.kind;x.data={...old,category:x.data.category};}else if(!valid(x))return Response.json({error:'Dados inválidos.'},{status:400});if(isSupabase()){await sbStore('save',x);return Response.json(x)}throw Error('Storage unavailable');}catch(e){console.error(e);return Response.json({error:'Não foi possível atualizar.'},{status:503});}}
export async function DELETE(req:Request){try{if(!sameOrigin(req))return Response.json({error:'Reabra o Livre para continuar.'},{status:403});const id=new URL(req.url).searchParams.get('id');if(!id)return Response.json({error:'Registro inválido.'},{status:400});const row:any=isSupabase()?(await sbStore('read')).records.find((r:any)=>r.id===id):null;if(row&&(isSupabase()?row.data:JSON.parse(row.data)).source==='pluggy')return Response.json({error:'Remova a conexão na tela Open Finance para apagar os dados importados.'},{status:400});if(isSupabase()){await sbStore('delete',{id});return Response.json({ok:true})}throw Error('Storage unavailable');}catch(e){console.error(e);return Response.json({error:'Não foi possível excluir.'},{status:503});}}
