'use client';
import {useState,useEffect} from 'react';
export default function Login(){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{const reason=new URLSearchParams(window.location.search).get('error');if(reason)setError(reason==='owner'?'Use a conta com o e-mail proprietário do Livre.':'Não foi possível entrar com esse provedor. Verifique sua ativação no Supabase e tente novamente.');},[]);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});if(!r.ok)throw Error((await r.json()).error);window.location.assign('/');}catch(e){setError(e instanceof Error?e.message:'Não foi possível entrar.');}finally{setBusy(false)}}
 return <main style={{minHeight:'100vh',display:'grid',placeItems:'center',padding:24,background:'#f6f7fb'}}><section className="panel" style={{width:'100%',maxWidth:420,padding:32}}><h1 style={{fontSize:32,fontWeight:800,color:'#6859e8'}}>Livre</h1><p style={{margin:'12px 0 24px'}}>Suas finanças, no seu controle.</p><div style={{display:"grid",gap:12,marginBottom:24}}><a className="secondary" style={{justifyContent:"center"}} href="/auth/start?provider=google">Continuar com Google</a><a className="secondary" style={{justifyContent:"center"}} href="/auth/start?provider=github">Continuar com GitHub</a></div><p style={{fontSize:12,marginBottom:16}}>Ou entre com e-mail e senha</p><form onSubmit={submit} className="bank-form"><label>E-mail<input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Senha<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy?'Entrando…':'Entrar'}</button></form><p style={{fontSize:12,marginTop:20}}>Use sua conta pessoal cadastrada no Supabase.</p></section></main>
}

