import {isSupabase,sbStore} from '../../../lib/storage';
import {checkOrigin,encryptCredentials,authenticate,verifyItem,syncConnection,bankError,BankError,validId} from '../../../lib/pluggy';
export async function GET(){try{const snapshot=isSupabase()?await sbStore('read'):null;const configured=!!(await sbStore('credentials_read')).encrypted;return Response.json({configured,connections:snapshot.connections,maxConnections:5},{headers:{'Cache-Control':'no-store'}})}catch(e){return bankError(e)}}
export async function POST(request:Request){try{checkOrigin(request);if(isSupabase())await sbStore('read');const data:any=await request.json();
 if(data.action==='configure'){if(typeof data.clientId!=='string'||typeof data.clientSecret!=='string'||!data.clientId.trim()||!data.clientSecret.trim()||data.clientId.length>200||data.clientSecret.length>500)throw new BankError('Preencha as duas credenciais da aplicação demo.');const credentials={clientId:data.clientId.trim(),clientSecret:data.clientSecret.trim()};await authenticate(credentials);const encrypted=await encryptCredentials(credentials);await sbStore('credentials_save',{encrypted});return Response.json({ok:true})}
 if(data.action==='add'){if(!validId(data.itemId)||typeof data.name!=='string'||!data.name.trim()||data.name.length>80)throw new BankError('Preencha um nome e o Item ID da conexão.');const apiKey=await authenticate();const item=await verifyItem(data.itemId,apiKey);const current:any=isSupabase()?{results:(await sbStore('read')).connections}:{results:[]};if(current.results.some((r:any)=>r.id===data.itemId))throw new BankError('Esta conexão já está cadastrada.',409);if(current.results.length>=5)throw new BankError('O limite pessoal é de cinco conexões.',409);if(isSupabase()){await sbStore('bank_add',{id:data.itemId,name:data.name.trim(),status:item.status||'READY',syncedAt:null});return Response.json({ok:true})}throw Error('Storage unavailable')}
 if(data.action==='sync'){if(!validId(data.itemId))throw new BankError('Conexão inválida.');return Response.json(await syncConnection(data.itemId))}
 throw new BankError('Ação inválida.');
 }catch(e){return bankError(e)}}
export async function DELETE(request:Request){try{checkOrigin(request);const id=new URL(request.url).searchParams.get('id');if(!validId(id))throw new BankError('Conexão inválida.');if(isSupabase()){await sbStore('bank_delete',{id});return Response.json({ok:true})}throw Error('Storage unavailable')}catch(e){return bankError(e)}}
